name: Update wiki pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Check out main repo
        uses: actions/checkout@v3

      - name: Check out wiki repo
        uses: actions/checkout@v3
        with:
          repository: "${{ github.repository }}.wiki"
          path: .wiki

      # - name: Setup Golang
      #   uses: actions/setup-go@v3
      # - name: Install protoc-gen-doc
      #   run: go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest
      # - name: Generate API documents
      #   run: protoc --doc_out=. --doc_opt=markdown,.wiki/api.md proto/*.proto

      # - name: Generate API documents
      #   run: docker run --rm -v $(pwd)/.wiki:/out -v $(pwd)/proto:/protos pseudomuto/protoc-gen-doc --doc_opt=markdown,API-documents.md

      - name: Generate API documents
        run: ./tools/gendoc.sh $GITHUB_WORKSPACE/.wiki

      - name: Stage and count changes
        working-directory: .wiki
        id: staging
        run: |
          git add .
          echo "NUM_OF_STAGED=$(git diff --staged --name-only | wc -l)" >> $GITHUB_OUTPUT

      - name: Commit wiki pages
        working-directory: .wiki
        if: steps.staging.outputs.NUM_OF_STAGED > 0
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -m "${GITHUB_WORKFLOW}"
          git push

